# -*- coding: utf-8 -*-
"""bkk.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C2y1CG-rGulQkLTECdhLG0mX7z43pULT
"""

from bs4 import BeautifulSoup
import pandas as pd
import requests
import re

url = "https://www.jobbkk.com/jobs/lists/1/%E0%B8%AB%E0%B8%B2%E0%B8%87%E0%B8%B2%E0%B8%99,%E0%B8%97%E0%B8%B1%E0%B9%89%E0%B8%87%E0%B8%AB%E0%B8%A1%E0%B8%94,%E0%B8%97%E0%B8%B8%E0%B8%81%E0%B8%88%E0%B8%B1%E0%B8%87%E0%B8%AB%E0%B8%A7%E0%B8%B1%E0%B8%94,%E0%B8%97%E0%B8%B1%E0%B9%89%E0%B8%87%E0%B8%AB%E0%B8%A1%E0%B8%94.html?occupationText=%E0%B9%84%E0%B8%AD%E0%B8%97%E0%B8%B5&sub_occu_all=210&occupation=25&occupation_sub=210&keyword_type=3&member_user_id=1"
response = requests.get(url)

page_html = BeautifulSoup(response.text, 'html.parser')

# print(page_html.prettify())

jobs = page_html.find_all('div', class_ = 'jobbkk-list-company')
companys =[]
names = []
locations = []
times = []
images = []

for container in jobs :
  cpn = container.find('a', title="company").get_text(strip=True)
  companys.append(cpn)
  
  time = container.find('a', href="#").get_text(strip=True)
  times.append(time)

  name = container.find('h6','applying').get_text(strip = True)
  names.append(name)

  for i in  container.find_all('div', class_="col-md-12 col-sm-12 col-xs-12 list-company-salary"):
    location = i.find('a','hover-work').get_text(strip=True)
    location  = location.split ()
    locations.append(location[1])

  image = container.find_all('img')
  for item in image:
    images.append(item['src'])

# print(len(companys))
# print(len(names))
# print(len(locations))
# print(len(times))
# print(len(images))

df = pd.DataFrame({
    'jobname' : names,
    'company' : companys,
    'location' : locations,
    'time' : times,
    'image' : images,
})

# print(df)

df.to_csv('bkk.csv', encoding = 'utf-8')

