# -*- coding: utf-8 -*-
"""db.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2nqQkH_3hNbFDq2vnioa2QOm2v3Fk64
"""

from bs4 import BeautifulSoup
import pandas as pd
import requests
import re

url = "https://th.jobsdb.com/th/th/job-list/%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B9%84%E0%B8%AD%E0%B8%97%E0%B8%B5/%E0%B8%99%E0%B8%B1%E0%B8%81%E0%B8%A7%E0%B8%B4%E0%B8%97%E0%B8%A2%E0%B8%B2%E0%B8%A8%E0%B8%B2%E0%B8%AA%E0%B8%95%E0%B8%A3%E0%B9%8C%E0%B8%82%E0%B9%89%E0%B8%AD%E0%B8%A1%E0%B8%B9%E0%B8%A5/1?fbclid=IwAR3F_aXOzgkfIG6FDMS-q_Z5YW7GjzYhuK4H7XWw40Eemlrmf4dyfSWlk7o"
response = requests.get(url)

page_html = BeautifulSoup(response.text, 'html.parser')

# print(page_html.prettify())

jobs = page_html.find_all('div', class_ = 'FYwKg _17IyL_0 _2-ij9_0 _3Vcu7_0 MtsXR_0')
names = []
locations = []
times = []
companys=[]
images = []

for container in jobs :
  name = container.find('div', class_ = 'FYwKg _2j8fZ_0 sIMFL_0 _1JtWu_0').get_text(strip = True)
  names.append(name)

  company = container.find('span', class_ = 'FYwKg _2Bz3E C6ZIU_0 _6ufcS_0 _2DNlq_0 _29m7__0').get_text(strip = True)
  companys.append(company)
  
  location = container.find('span','FYwKg _3MPd_ _2Bz3E And8z').get_text(strip = True)
  locations.append(location)

  time = container.find('time').get_text(strip = True)
  times.append(time)
  
  image = container.find_all('img',class_ ='FYwKg _1qfRc_0')
  if image is not None:
    images.append(image['src'])
  else: 
    images.append("")

print(len(companys))
print(len(names))
print(len(locations))
print(len(times))
print(len(images))

df = pd.DataFrame({
    '่jobname' : names,
    'company' : companys,
    'location' : locations,
    'time' : times,
    'image' : images,
})

df

df.to_csv('DB.csv', encoding='utf-8')

