# -*- coding: utf-8 -*-
"""indeed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uLBZ426IyV72HfatXNmoNSndDWsH2ZnI
"""

from bs4 import BeautifulSoup
import pandas as pd
import requests
import re

url = "https://th.indeed.com/%E0%B8%87%E0%B8%B2%E0%B8%99data-scientist"
response = requests.get(url)

page_html = BeautifulSoup(response.text, 'html.parser')

# print(page_html.prettify())

jobs = page_html.find_all('div', class_ = 'sjcl')
t = page_html.find_all('div', class_ = 'result-link-bar')
n = page_html.find_all('h2', class_ = 'title')
names = []
locations = []
times = []
companys=[]

for container in jobs :
  company = container.find('span','company').get_text(strip = True)
  companys.append(company)

  location = container.find('span','location accessible-contrast-color-location').get_text(strip = True)
  locations.append(location)

for container in t :
  time = container.find('span', 'date date-a11y').get_text(strip = True)
  times.append(time)

for container in n :
  name = container.find('a').get_text(strip = True)
  names.append(name)

# print(len(locations))
# print(len(companys))
# print(len(times))
# print(len(names))

df = pd.DataFrame({    
    'jobname' : names,
    'company' : companys,
    'location' : locations,
    'time' : times,
})

# print(df)

df.to_csv('indeed.csv', encoding='utf-8')

