# -*- coding: utf-8 -*-
"""jobthai.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kRx01y0l3g3T1rJOqZk93uT1hSW4bsoF
"""

from bs4 import BeautifulSoup
import pandas as pd
import requests
import re

url = 'https://www.jobthai.com/%E0%B8%AB%E0%B8%B2%E0%B8%87%E0%B8%B2%E0%B8%99/%E0%B8%87%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B8%AD%E0%B8%A1%E0%B8%9E%E0%B8%B4%E0%B8%A7%E0%B9%80%E0%B8%95%E0%B8%AD%E0%B8%A3%E0%B9%8C-it-%E0%B9%82%E0%B8%9B%E0%B8%A3%E0%B9%81%E0%B8%81%E0%B8%A3%E0%B8%A1%E0%B9%80%E0%B8%A1%E0%B8%AD%E0%B8%A3%E0%B9%8C,data-scientist'
response = requests.get(url)

page_html = BeautifulSoup(response.text, 'html.parser')

# print(page_html.prettify())

jobs = page_html.find_all('div',class_='ant-row jobItem__Container-msklqa-8 fxvUXX')
names = []
companys = []
locations = []
times = []
pictures = []

for container in jobs :
  n = container.find('h2',"label-ohgq7e-0 kCdcpK").get_text(strip=True)
  names.append(n)

  c = container.find('h2','label-ohgq7e-0 ffBpGJ').get_text(strip=True)
  companys.append(c)

  l = container.find(id = 'location-text').get_text(strip=True)
  locations.append(l)

  t = container.find(style = 'text-align:right').span.get_text(strip=True)
  times.append(t)

  p = container.find('picture').img
  p2 = p['src']
  pictures.append(p2)

# print(len(locations))
# print(len(companys))
# print(len(times))
# print(len(names))
# print(len(pictures))


df = pd.DataFrame({
    'jobname': names,
    'company': companys,
    'location': locations,
    'time' : times,
    'image' : pictures
})

# print(df)

df.to_csv('jobthai.csv')

